travis:
  secure:
    BINSTAR_TOKEN: a7+GHYW/DOwX90poGEdPzeVlUTvkUl6LjFjObwuyvqdZMgvPbQbhuInQjC3kVTTrSXUZjLLeeAdRiVpRrk2UAzh0caA9Tv0+5JNMm5K4Fv4Hly3cSWJjGZe6M3b1PTnSJtKonJ5Ra0leqG1Ksz4HhT0YTIclgCOG7wnsBbBs/D0V4KM3fzOAGwfLD1o1sKpWiMaaERTFXeMnef2EEtbV7NS2kmrEpFoOQ29v0Z7sI5MdAZUtY4U7gywpwh0NL3eU4536dDYzdb7QGLx+B8cmsGN1JV/dvr3MozR0JQIKjpDEpekJR+G1arofmVtO3h36S/oBBo+TvuwLn6309U5gwbIc03cCHAWEnqR7V+CSeHwuZ2rj2c4+7Q6bvAXJL6CTRVufvO4VZ/XXX0nVk5mTvJ2wIuvt+uEBUw7K5aYGixn7jIkt940WAQIU9xy/hdU+6OJqCt1KTGhaFVB1Wfr7bfWPvier6j92YnrZzxG9jct/USoMmeaX/plH5qToUPxtB86SgAjY3WiDLYzOG3c3MslFC6wcFxb7IOvAcI601KlgyiRJZq0z0iKuIRl/zEGgUYNsQcKtJAhvLwLNX/3t9a5JzpYaaffUMNNZ9A3B4cSw/QCkDv2Q5M43AIXOQnWC3BRqBz/QdnRzOl8p5UZnxQVzGCSX9xZb7P2mJum5D/s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
